### ISSUE TITLE
Test fails

### ISSUE THREAD

**Issue by MohamadHarastani** [scipion-em/scipion-em-tomotwin#4]
The test of tomotwin failed on my computer. The protocols are there, but the assertion failed. Could it be that the assertion is not accounting for random output?

```
(base) harastamadm@PC4-0002-D:/shared/scipion3/plugins$  scipion3 tests tomotwin.tests.test_protocols_tomotwin
Scipion v3.0.12 - Eugenius
Running tests....
Creating project at /media/SharedDisk/ScipionProjects/projects/TestTomoTwinRefPicking/project.sqlite
>>>> python3 /shared/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/apps/pw_sync_data.py --download emd_10439 
Selected datasets: emd_10439
Dataset emd_10439 not in local machine. Downloading...
Fetching files of dataset "emd_10439"...
#################################################** Running command: 'python3 /shared/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/apps/pw_protocol_run.py "/media/SharedDisk/ScipionProjects/projects/TestTomoTwinRefPicking" "Runs/000002_ProtImportTomograms/logs/run.db" 2'
** Running command: 'python3 /shared/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/apps/pw_protocol_run.py "/media/SharedDisk/ScipionProjects/projects/TestTomoTwinRefPicking" "Runs/000073_ProtImportVolumes/logs/run.db" 73'
** Running command: 'python3 /shared/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/apps/pw_protocol_run.py "/media/SharedDisk/ScipionProjects/projects/TestTomoTwinRefPicking" "Runs/000137_ProtTomoTwinRefPicking/logs/run.db" 137'
[   FAILED ] TestTomoTwinRefPicking.test_run


Traceback (most recent call last):
  File "/shared/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/shared/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/shared/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "/shared/scipion3/plugins/scipion-em-tomotwin/tomotwin/tests/test_protocols_tomotwin.py", line 68, in test_run
    self.assertAlmostEqual(outputCoords.getSize(), 3192, delta=30)
  File "/shared/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 966, in assertAlmostEqual
    raise self.failureException(msg)
AssertionError: 2969 != 3192 within 30 delta (223 difference)
```

**Comment by azazellochg** [comment]
plugin updated to the latest software version, the test is working properly. Thanks for the report!
